[[redirects]]
  from = "/servidor/*"
  to = "https://proyecto-bog-backend.onrender.com/servidor/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/posts/*"
  to = "https://proyecto-bog-backend.onrender.com/servidor/posts/:splat"
  status = 200
  force = true

  [[redirects]]
  from = "/login/*"
  to = "https://proyecto-bog-backend.onrender.com/servidor/login/:splat"
  status = 200
  force = true

   [[redirects]]
  from = "/register/*"
  to = "https://proyecto-bog-backend.onrender.com/servidor/register/:splat"
  status = 200
  force = true

   [[redirects]]
  from = "/logout/*"
  to = "https://proyecto-bog-backend.onrender.com/servidor/logout/:splat"
  status = 200
  force = true