[[redirects]]
  from = "/servidor/*"
  to = "https://proyecto-bog-backend.onrender.com/servidor/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/posts/*"
  to = "https://proyecto-bog-backend.onrender.com/servidor/posts/:splat"
  status = 200
  force = true