[build]
  publish = "build"
  command = "npm run build"

  [[redirects]]
  from = "/posts/*"
  to = "https://proyecto-bog-backend.onrender.com/servidor/posts/:splat"
  status = 200
  force = true